*EDA Y ETL DEL MODELO

In [3]:
#importar bibliotecas necesarias 
import pandas as pd
import numpy as np

In [4]:
# Cargar el dataset
data = pd.read_csv('movies_clean.csv', low_memory= False)

In [5]:
data

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,production_companies,production_countries,release_date,...,title,vote_average,vote_count,cast,director,release_year,release_month,release_day,return,earns
0,toy story collection,30000000.0,"animation, comedy, family",862,en,"led by woody, andy's toys live happily in his ...",21.946943,pixar animation studios,united states of america,1995-10-30,...,toy story,7.7,5415.0,"tom hanks, tim allen, don rickles, jim varney,...",john lasseter,1995,10,30,12.451801,343554033.0
1,sin informacion,65000000.0,"adventure, fantasy, family",8844,en,when siblings judy and peter discover an encha...,17.015539,"tristar pictures, teitler film, interscope com...",united states of america,1995-12-15,...,jumanji,6.9,2413.0,"robin williams, jonathan hyde, kirsten dunst, ...",joe johnston,1995,12,15,4.043035,197797249.0
2,grumpy old men collection,0.0,"romance, comedy",15602,en,a family wedding reignites the ancient feud be...,11.712900,"warner bros., lancaster gate",united states of america,1995-12-22,...,grumpier old men,6.5,92.0,"walter matthau, jack lemmon, ann-margret, soph...",howard deutch,1995,12,22,0.000000,0.0
3,sin informacion,16000000.0,"comedy, drama, romance",31357,en,"cheated on, mistreated and stepped on, the wom...",3.859495,twentieth century fox film corporation,united states of america,1995-12-22,...,waiting to exhale,6.1,34.0,"whitney houston, angela bassett, loretta devin...",forest whitaker,1995,12,22,5.090760,65452156.0
4,father of the bride collection,0.0,comedy,11862,en,just when george banks has recovered from his ...,8.387519,"sandollar productions, touchstone pictures",united states of america,1995-02-10,...,father of the bride part ii,5.7,173.0,"steve martin, diane keaton, martin short, kimb...",charles shyer,1995,2,10,0.000000,76578911.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45446,sin informacion,0.0,"drama, action, romance",30840,en,"yet another version of the classic epic, with ...",5.683753,"westdeutscher rundfunk (wdr), working title fi...","canada, germany, united kingdom, united states...",1991-05-13,...,robin hood,5.7,26.0,"patrick bergin, uma thurman, david morrissey, ...",john irvin,1991,5,13,0.000000,0.0
45447,sin informacion,0.0,drama,111109,tl,an artist struggles to finish his work while a...,0.178241,sine olivia,philippines,2011-11-17,...,century of birthing,9.0,3.0,"angel aquino, perry dizon, hazel orencio, joel...",lav diaz,2011,11,17,0.000000,0.0
45448,sin informacion,0.0,"action, drama, thriller",67758,en,"when one of her hits goes wrong, a professiona...",0.903007,american world pictures,united states of america,2003-08-01,...,betrayal,3.8,6.0,"erika eleniak, adam baldwin, julie du page, ja...",mark l. lester,2003,8,1,0.000000,0.0
45449,sin informacion,0.0,NaN,227506,en,"in a small town live two brothers, one a minis...",0.003503,yermoliev,russia,1917-10-21,...,satan triumphant,0.0,0.0,"iwan mosschuchin, nathalie lissenko, pavel pav...",yakov protazanov,1917,10,21,0.000000,0.0
45450,sin informacion,0.0,NaN,461257,en,50 years after decriminalisation of homosexual...,0.163015,NaN,united kingdom,2017-06-09,...,queerama,0.0,0.0,NaN,daisy asquith,2017,6,9,0.000000,0.0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45451 entries, 0 to 45450
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  45451 non-null  object
 1   budget                 45451 non-null  float64
 2   genres                 43067 non-null  object
 3   id                     45451 non-null  int64
 4   original_language      45451 non-null  object
 5   overview               45451 non-null  object
 6   popularity             45451 non-null  float64
 7   production_companies   33634 non-null  object
 8   production_countries   39232 non-null  object
 9   release_date           45451 non-null  object
 10  revenue                45451 non-null  float64
 11  runtime                45451 non-null  float64
 12  spoken_languages       45230 non-null  object
 13  status                 45451 non-null  object
 14  title                  45451 non-null  object
 15  vote_average           45451 non-null  float64
 16  vote_count             45451 non-null  float64
 17  cast                   43097 non-null  object
 18  director               45451 non-null  object
 19  release_year           45451 non-null  int64
 20  release_month          45451 non-null  int64
 21  release_day            45451 non-null  int64
 22  return                 45451 non-null  float64
 23  earns                  45451 non-null  float64
dtypes: float64(8), int64(4), object(12)
memory usage: 8.3+ MB

In [7]:
data.drop('id',axis = "columns",inplace = True)
data.drop('overview',axis = "columns",inplace = True)
data.drop('budget',axis = "columns",inplace = True)
data.drop('revenue',axis = "columns",inplace = True)
data.drop('production_countries',axis = "columns",inplace = True)
data.drop('spoken_languages',axis = "columns",inplace = True)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45451 entries, 0 to 45450
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  45451 non-null  object
 1   genres                 43067 non-null  object
 2   original_language      45451 non-null  object
 3   popularity             45451 non-null  float64
 4   production_companies   33634 non-null  object
 5   release_date           45451 non-null  object
 6   runtime                45451 non-null  float64
 7   status                 45451 non-null  object
 8   title                  45451 non-null  object
 9   vote_average           45451 non-null  float64
 10  vote_count             45451 non-null  float64
 11  cast                   43097 non-null  object
 12  director               45451 non-null  object
 13  release_year           45451 non-null  int64
 14  release_month          45451 non-null  int64
 15  release_day            45451 non-null  int64
 16  return                 45451 non-null  float64
 17  earns                  45451 non-null  float64
dtypes: float64(6), int64(3), object(9)
memory usage: 6.2+ MB

In [9]:
data['release_date'] = pd.to_datetime(data['release_date'])

#A continuacion e realiza una categorizacion de valores numericos a variables cuantitativos

In [10]:
data['popularity'] = pd.qcut(data['popularity'],q = 5, labels=['Desconocida','Conocida', 'Popular','Muy Popular','Obra Maestra'])
data['vote_average'] = pd.qcut(data['vote_average'],q = 4, labels=['Mala','Buena','Muy Buena','Excelente'])
data['runtime'] = pd.qcut(data['runtime'],q = 3, labels=['Poca Duracion', 'Media Duracion', 'Larga Duracion'])
data['release_date'] = (data['release_date'].dt.year//10)*10

#*Ahora se convierten todas las columnas a variables categoricas representadas en numeros

In [11]:
data['belongs_to_collection'] = pd.Categorical(data['belongs_to_collection']).codes
data['genres'] = pd.Categorical(data['genres']).codes
data['original_language'] = pd.Categorical(data['original_language']).codes
data['production_companies'] = pd.Categorical(data['production_companies']).codes
data['status'] = pd.Categorical(data['status']).codes
data['popularity'] = pd.Categorical(data['popularity']).codes
data['vote_average'] = pd.Categorical(data['vote_average']).codes
data['release_date'] = pd.Categorical(data['release_date']).codes
data['runtime'] = pd.Categorical(data['runtime']).codes

#* Se hace el diagrama de correlacion para verificar la redundancia de los datos

In [13]:
corr = data.corr()
corr.style.background_gradient(cmap='coolwarm')

/var/folders/cf/5nv863qj24s_gxr8p3cmtljr0000gn/T/ipykernel_2382/1398619703.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr = data.corr()

In [14]:
data.head()

,belongs_to_collection,genres,original_language,popularity,production_companies,release_date,runtime,status,title,vote_average,vote_count,cast,director,release_year,release_month,release_day,return,earns
0,1547,1078,17,4,15290,12,0,4,toy story,3,5415.0,"tom hanks, tim allen, don rickles, jim varney,...",john lasseter,1995,10,30,12.451801,343554033.0
1,1119,942,17,4,19772,12,2,4,jumanji,3,2413.0,"robin williams, jonathan hyde, kirsten dunst, ...",joe johnston,1995,12,15,4.043035,197797249.0
2,530,3293,17,4,21779,12,1,4,grumpier old men,2,92.0,"walter matthau, jack lemmon, ann-margret, soph...",howard deutch,1995,12,22,0.000000,0.0
3,1119,1387,17,3,19893,12,2,4,waiting to exhale,2,34.0,"whitney houston, angela bassett, loretta devin...",forest whitaker,1995,12,22,5.090760,65452156.0
4,435,1228,17,4,16878,12,2,4,father of the bride part ii,1,173.0,"steve martin, diane keaton, martin short, kimb...",charles shyer,1995,2,10,0.000000,76578911.0

In [ ]:
data.to_csv('data_ML.csv', index=False)